<#
.SYNOPSIS
    Cleans up GitHub Copilot CPU profile files from the TEMP directory.

.DESCRIPTION
    This script removes .cpuprofile files generated by GitHub Copilot extensions.
    It displays detailed information about each file found and deleted, including
    file names, sizes, and ages.

.NOTES
    These files can accumulate over time and consume disk space.
#>

$title = "[0440_Cleanup_cpuprofile]"

Write-Host "$title Scanning for .cpuprofile files in $env:TEMP..." -ForegroundColor Cyan

# Find all .cpuprofile files
$allFiles = Get-ChildItem "$env:TEMP\*.cpuprofile" -ErrorAction SilentlyContinue

if ($allFiles.Count -eq 0) {
    Write-Host "$title No .cpuprofile files found." -ForegroundColor Green
    exit 0
}

Write-Host "$title Found $($allFiles.Count) .cpuprofile file(s):" -ForegroundColor Yellow

$totalSize = 0
$deletedCount = 0
$failedCount = 0

foreach ($file in $allFiles) {
    $fileAge = (Get-Date) - $file.LastWriteTime
    $fileSizeMB = [math]::Round($file.Length / 1MB, 2)
    $totalSize += $file.Length
    
    Write-Host ("  - {0} ({1} MB, {2} days old)" -f $file.Name, $fileSizeMB, [int]$fileAge.TotalDays) -ForegroundColor Gray
    
    try {
        Remove-Item $file.FullName -Force -ErrorAction Stop
        Write-Host "    [DELETED]" -ForegroundColor Green
        $deletedCount++
    }
    catch {
        Write-Host "    [FAILED] $($_.Exception.Message)" -ForegroundColor Red
        $failedCount++
    }
}

$totalSizeMB = [math]::Round($totalSize / 1MB, 2)

Write-Host "`n$title Summary:" -ForegroundColor Cyan
Write-Host "  Total files found    : $($allFiles.Count)" -ForegroundColor White
Write-Host "  Successfully deleted : $deletedCount" -ForegroundColor Green
Write-Host "  Failed to delete     : $failedCount" -ForegroundColor $(if ($failedCount -gt 0) { 'Red' } else { 'White' })
Write-Host "  Total space freed    : $totalSizeMB MB" -ForegroundColor Green

if ($deletedCount -gt 0) {
    Write-Host "`n$title Cleanup completed successfully." -ForegroundColor Green
} else {
    Write-Host "`n$title No files were deleted." -ForegroundColor Yellow
}